In [2]:
import time

In [6]:
timestamp = int(time.time())
print(timestamp)

1554880197


In [8]:
struct_time = time.localtime(timestamp)
print(struct_time)

time.struct_time(tm_year=2019, tm_mon=4, tm_mday=10, tm_hour=15, tm_min=9, tm_sec=57, tm_wday=2, tm_yday=100, tm_isdst=0)


In [17]:
# 字典特征抽取
from sklearn.feature_extraction import DictVectorizer

# 人物信息
people = [{"name":"袁小棠", "age": 19, "gender":"男"},
            {"name":"小亭子", "age": 19, "gender":"女"},
            {"name":"白衣段云", "age": 22, "gender": "男"},
            {"name":"阿九", "age": 18, "gender":"女"}]
for i in range(people.__len__()):
    print(people[i])

{'name': '袁小棠', 'age': 19, 'gender': '男'}
{'name': '小亭子', 'age': 19, 'gender': '女'}
{'name': '白衣段云', 'age': 22, 'gender': '男'}
{'name': '阿九', 'age': 18, 'gender': '女'}


In [12]:
# 实例化字典特征抽取对象(为了便于观察,不使用sparse格式显示)
dict_v = DictVectorizer(sparse=False)
# 填充数值并转换
data = dict_v.fit_transform(people)

In [13]:
# 打印抽取后的,字典特征名称信息
print(dict_v.get_feature_names())

['age', 'gender=女', 'gender=男', 'name=小亭子', 'name=白衣段云', 'name=袁小棠', 'name=阿九']


In [14]:
# 打印字典特征数据信息
print(data)

[[19.  0.  1.  0.  0.  1.  0.]
 [19.  1.  0.  1.  0.  0.  0.]
 [22.  0.  1.  0.  1.  0.  0.]
 [18.  1.  0.  0.  0.  0.  1.]]


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
import jieba

In [43]:
# 肖申克影评
xsk_text = """
豆瓣有人问，为啥肖申克评价这么高？
他是不是只是从一个满是泥泞的臭水沟的监牢逃出而已？
其实救赎是对自己的破茧成蝶，每个人眼前都有一个模版，
一个完美的人的样子，很美，很有灵魂，很有姿态，得到很多人爱。
为什么自己总是做不好，自己总是不美？自己总是如此多的陋习？
但是最后这一个人还是只能从自己的茧里面冲破而出，或许学会了飞，或许意境忘了怎么飞，
但这个速度的快慢不会影响最早的结果，最终你还是要学会怎么从丑陋变得自信和自强～ 
接受一个事实，在某个层面上，在三维时空看起来，蝴蝶都是一样的美，蝴蝶其实根本上长得一样～ 
"""
# 中文分词
xsk = jieba.cut(xsk_text)
xsk_list = [x for x in xsk]
print(xsk_list)

['\n', '豆瓣', '有人', '问', '，', '为啥', '肖申克', '评价', '这么', '高', '？', '\n', '他', '是不是', '只是', '从', '一个', '满是', '泥泞', '的', '臭水沟', '的', '监牢', '逃出', '而已', '？', '\n', '其实', '救赎', '是', '对', '自己', '的', '破', '茧', '成蝶', '，', '每个', '人', '眼前', '都', '有', '一个', '模版', '，', '\n', '一个', '完美', '的', '人', '的', '样子', '，', '很', '美', '，', '很', '有', '灵魂', '，', '很', '有', '姿态', '，', '得到', '很多', '人爱', '。', '\n', '为什么', '自己', '总是', '做', '不好', '，', '自己', '总是', '不美', '？', '自己', '总是', '如此', '多', '的', '陋习', '？', '\n', '但是', '最后', '这', '一个', '人', '还是', '只能', '从', '自己', '的', '茧', '里面', '冲破', '而出', '，', '或许', '学会', '了', '飞', '，', '或许', '意境', '忘', '了', '怎么', '飞', '，', '\n', '但', '这个', '速度', '的', '快慢', '不会', '影响', '最早', '的', '结果', '，', '最终', '你', '还是', '要', '学会', '怎么', '从', '丑陋', '变得', '自信', '和', '自强', '～', ' ', '\n', '接受', '一个', '事实', '，', '在', '某个', '层面', '上', '，', '在', '三维', '时空', '看起来', '，', '蝴蝶', '都', '是', '一样', '的', '美', '，', '蝴蝶', '其实', '根本', '上长', '得', '一样', '～', ' ', '\n']


In [39]:
# 实例化文本特征抽取
countvec = CountVectorizer()
# 填充并转换数据
data = countvec.fit_transform(xsk_list)

In [40]:
# 打印抽取的特征名
print(countvec.get_feature_names())

['一个', '一样', '三维', '上长', '不会', '不好', '不美', '丑陋', '为什么', '为啥', '事实', '人爱', '但是', '其实', '冲破', '变得', '只是', '只能', '如此', '姿态', '学会', '完美', '层面', '影响', '很多', '得到', '快慢', '怎么', '总是', '意境', '成蝶', '或许', '接受', '救赎', '时空', '是不是', '最后', '最早', '最终', '有人', '某个', '样子', '根本', '模版', '每个', '泥泞', '满是', '灵魂', '监牢', '看起来', '眼前', '结果', '而出', '而已', '肖申克', '自信', '自己', '自强', '臭水沟', '蝴蝶', '评价', '豆瓣', '还是', '这个', '这么', '逃出', '速度', '里面', '陋习']


In [42]:
# 将数据以类one_hot编码方式展示
print(data.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
import concurrent
import os
from concurrent.futures import ThreadPoolExecutor
import requests
from bs4 import BeautifulSoup

headers = {
    'Host': 'www.mzitu.com',
    'Pragma': 'no-cache',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.8,en;q=0.6',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36',
    'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8',
    'Referer': 'https://www.baidu.com/s?wd=%E5%A6%B9%E5%AD%90%E5%9B%BE&rsv_spt=1&rsv_iqid=0xe7f5238400078530&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=&tn=baiduhome_pg&ch=&rsv_enter=1&inputT=8081'
}

response = requests.get('https://www.mzitu.com/page/1', headers=headers)
html = response.text
print(response.status_code)
soup = BeautifulSoup(html, 'lxml')
print(html[:500])

200
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>妹子图 - 性感美女图片每日更新</title>
<meta name="keywords" content="妹子图,妹子,美女图片,性感美女,美女写真" />
<meta name="description" content="妹子图官网(www.mzitu.com)每日分享最新最全的妹子图片和高清性感美女图片，包括性感妹子、日本妹子、台湾妹子、清纯妹子、妹子自拍以及街拍美女图片。" />
<script type="text/javascript" src="https://ip.ws.126.net/ipquery?"></script>
<script type="text/javascript" src="https://i.meizitu.net/pfiles/loc.js"></script>
<meta name="mobile-agent" content


In [52]:
# 生成html
from pyecharts.charts import Bar
from pyecharts import options as opts

bar = (
    Bar()
    .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
    .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
    .set_global_opts(title_opts=opts.TitleOpts(title="某商场销售情况"))
)
# 'C:\\Users\\stone0\\jupyter\\render.html'
bar.render('./crawler/render.html')

'C:\\Users\\stone0\\jupyter\\crawler\\render.html'

In [54]:
# 生成图片
from snapshot_selenium import snapshot as driver

from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.render import make_snapshot


def bar_chart() -> Bar:
    c = (
        Bar()
        .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
        .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
        .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
        .reversal_axis()
        .set_series_opts(label_opts=opts.LabelOpts(position="right"))
        .set_global_opts(title_opts=opts.TitleOpts(title="Bar-测试渲染图片"))
    )
    return c

# 需要安装 snapshot_selenium
make_snapshot(driver, bar_chart().render('./crawler/png_render.html'), "./crawler/bar.png")

In [1]:
# 在顶部声明 Notebook 类型，必须在引入 pyecharts.charts 等模块前声明
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
from pyecharts.charts import Bar
from pyecharts import options as opts

In [2]:
bar = (
    Bar()
    .add_xaxis(["衬衫", "毛衣", "领带", "裤子", "风衣", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [114, 55, 27, 101, 125, 27, 105])
    .add_yaxis("商家B", [57, 134, 137, 129, 145, 60, 49])
    .set_global_opts(title_opts=opts.TitleOpts(title="某商场销售情况"))
)

In [3]:
bar.load_javascript()
# jupyter labextension install @jupyterlab/plotly-extension

In [4]:
bar.render_notebook()

In [5]:
import plotly
from plotly.graph_objs import Scatter, Layout
plotly.offline.init_notebook_mode(connected=True)

In [6]:
import plotly.offline as py
from plotly.graph_objs import Scatter, Layout
import plotly.graph_objs as go
 
py.init_notebook_mode(connected=True)
 
trace1=go.Scatter(
    x=[1,2],
    y=[1,2]
)
trace2=go.Scatter(
    x=[1,2],
    y=[2,1]
)
py.iplot([trace1, trace2])

In [110]:
import jieba
s1 = '你今天吃饭了吗'
a1 = '吃饭'
a2 = '睡觉'

# 精确模式
seg_list = jieba.cut(s1, cut_all=False)
# print("【精确模式】：" + "|".join(seg_list))
# s = []
# for i in seg_list:
#     print(i)
#     s.append(i)
# s
s1_cut = [i for i in jieba.cut(s1, cut_all=False) if i != '']
print(s1_cut)
a1 = [a1]
print(a1)

['你', '今天', '吃饭', '了', '吗']
['吃饭']


In [111]:
s = set(s1_cut).union(set(a1))
print(s)

{'吗', '你', '今天', '了', '吃饭'}


In [112]:
d = dict()
j = 0
for i in s:
    print(i)
    d[i]=j
    j+=1
print(d)

吗
你
今天
了
吃饭
{'吗': 0, '你': 1, '今天': 2, '了': 3, '吃饭': 4}


In [143]:
print('s1cut: ' + str(s1_cut))
print('d: ' + str(d))

cut_code = []
for i in s1_cut:
#     print(d[i])
    cut_code.append(d[i])
# cut_code = [d[i] for i in s1_cut]
print('cutcode: ' + str(cut_code))

cut_code = [0]*len(d)
print('cutcode: ' + str(cut_code))

# for i in s1_cut:
#     cut_code[d[i]]+=1
# print('newcutcode: ' + str(cut_code))

for i in s1_cut:
    print(i, d[i])
    cut_code[d[i]]+=1
    print(cut_code[d[i]])



s1cut: ['你', '今天', '吃饭', '了', '吗']
d: {'吗': 0, '你': 1, '今天': 2, '了': 3, '吃饭': 4}
cutcode: [1, 2, 4, 3, 0]
cutcode: [0, 0, 0, 0, 0]
你 1
1
今天 2
1
吃饭 4
1
了 3
1
吗 0
1


In [126]:
a1_code = []
for i in a1:
    print(i)
    print(d[i])

吃饭
4


In [10]:
import jieba
import math
s1 = '你今天吃饭了吗'
s1_cut = [i for i in jieba.cut(s1, cut_all=True) if i != '']
s2 = '午饭'
s2_cut = [i for i in jieba.cut(s2, cut_all=True) if i != '']
print(s1_cut)
print(s2_cut)
word_set = set(s1_cut).union(set(s2_cut))
print(word_set)

word_dict = dict()
i = 0
for word in word_set:
    word_dict[word] = i
    i += 1
print(word_dict)

s1_cut_code = [word_dict[word] for word in s1_cut]
print(s1_cut_code)
s1_cut_code = [0]*len(word_dict)

for word in s1_cut:
    s1_cut_code[word_dict[word]]+=1
print('one hot: ' + str(s1_cut_code))

s2_cut_code = [word_dict[word] for word in s2_cut]
print(s2_cut_code)
s2_cut_code = [0]*len(word_dict)
for word in s2_cut:
    s2_cut_code[word_dict[word]]+=1
print('one hot: ' + str(s2_cut_code))

# 计算余弦相似度
sum = 0
sq1 = 0
sq2 = 0
for i in range(len(s1_cut_code)):
    sum += s1_cut_code[i] * s2_cut_code[i]
    sq1 += pow(s1_cut_code[i], 2)
    sq2 += pow(s2_cut_code[i], 2)

try:
    result = round(float(sum) / (math.sqrt(sq1) * math.sqrt(sq2)), 2)
except ZeroDivisionError:
    result = 0.0
print(result)

['你', '今天', '吃饭', '了', '吗']
['午饭']
{'了', '今天', '吃饭', '吗', '你', '午饭'}
{'了': 0, '今天': 1, '吃饭': 2, '吗': 3, '你': 4, '午饭': 5}
[4, 1, 2, 0, 3]
one hot: [1, 1, 1, 1, 1, 0]
[5]
one hot: [0, 0, 0, 0, 0, 1]
0.0


In [12]:
import pandas as pd
import numpy as np

gsdf = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                   'name': ['aaa', 'bbb', np.NaN, 'bbb', 'ddd'],
                   'sex': ['Female', 'Male', 'Male', 'Male', 'Female'],
                   'age': [23, 24, 24, 25, 24]})
gsdf

id name     sex  age
0   1  aaa  Female   23
1   2  bbb    Male   24
2   3  NaN    Male   24
3   4  bbb    Male   25
4   5  ddd  Female   24

In [9]:
# 分组排序
gsgb = gsdf.groupby(by='age').size()
print(gsgb)

print()
dfgb = pd.DataFrame({'age':gsgb.index,'nums':gsgb.values})
print(dfgb)

dfgb.sort_values(['nums'], ascending=False).head()

age
23    1
24    3
25    1
dtype: int64

   age  nums
0   23     1
1   24     3
2   25     1


age  nums
1   24     3
0   23     1
2   25     1

In [13]:
# 查找空值
gsdf[gsdf.isnull().values==True].head()

id name   sex  age
2   3  NaN  Male   24

In [14]:
gsdf.dropna()

id name     sex  age
0   1  aaa  Female   23
1   2  bbb    Male   24
3   4  bbb    Male   25
4   5  ddd  Female   24

In [216]:
# 实现复制df后修改不影响原df, copy出来的df会有新的id, 直接使用=是引用, 修改会影响所引用的df
s = pd.DataFrame({"id":[101,102,103,104,105],
                  "name":['张三','李四','王五','赵六','陈七'],
                  "age":[18,17,np.nan,18,17],
                  "sex":['女','男','男',np.nan,'女'],
                  "score":[69,59,70,40,np.nan]},
                columns=['id','name','age','sex','score'])
print('原df:\n', s)

# 复制
d = s['id'].copy()
print('\n复制df:\n', d)

# 修改
d[0] = 111
print('\n修改df:\n', d)

# 原df
print('\n原df:\n', s)

原df:
     id name   age  sex  score
0  101   张三  18.0    女   69.0
1  102   李四  17.0    男   59.0
2  103   王五   NaN    男   70.0
3  104   赵六  18.0  NaN   40.0
4  105   陈七  17.0    女    NaN

复制df:
 0    101
1    102
2    103
3    104
4    105
Name: id, dtype: int64

修改df:
 0    111
1    102
2    103
3    104
4    105
Name: id, dtype: int64

原df:
     id name   age  sex  score
0  101   张三  18.0    女   69.0
1  102   李四  17.0    男   59.0
2  103   王五   NaN    男   70.0
3  104   赵六  18.0  NaN   40.0
4  105   陈七  17.0    女    NaN


In [2]:
import pandas as pd
import pkuseg
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
# “dog cat fish” 为输入列表元素,即代表一个文章的字符串
# texts = ['股价 连续 涨停 股东 拟 减持 双 科技 涉嫌 提前 泄露 未 公开 信息 炒作 股价 配合 股东 减持 遭 深交所 问询 恒泰艾普 300157) 两 高 涉嫌 违规 减持 瞒天 海1年 曝光 酒鬼酒 000799)子公司 账户 1亿 存款 盗 报案']
texts = ['股价 连续 涨停 股东 拟 减持 双 科技 涉嫌 提前 泄露 未 公开 信息 炒作 股价'
         ,'搜索引擎 输入 [ 尚赫 ] 发现 篇 [ 尚赫 ] 涉嫌 传销 虚假 宣传 跨 区 经营'
         ,'综艺股份 大兴 服装 拟 减持 公司 超 2%股份 [ 科新机电 ] 300092) 上市'
         ,'[ 四川双马 ] 000935)待注 资产 缩水 盈利 预测 下滑 [ 广电运通 ] 002'
         ,'    [ 宝象金融 ] 涉嫌 自融 项目 造假 请 停止 犯罪 信达 金控 字 介绍 又是 套路'
         ,'[ 铁岭新城 ] 000809) 股东 减持 2805万股 占 5. 1% [ 恒邦股份 ]'
         ,'三大 原因 [ 惠而浦 ] 会计 差错 前两年 净利 更正 减少 1. 89亿 [ 远程电缆'
         ,'[ 佛山照明 ] 000541) 董事长 辞职 [ 创兴资源 ] 600193) 虚假 陈述'
         ,'文章 深圳 检方 通报 翁涛 [ 深圳光彩投资控股集团有限公司 ] 社会 发行 虚拟 货币'
         ,'武生物( 300357) 股东 东方 富海 减持 公司 1. 2%股份 [ 同洲电子 ] 0'
         ,' 华尔街 依然 喜欢 [ 通用 ] 电气 位 分析师 建议 卖出 [ 紫光古汉 ] 00059'
         ,' [ 东北制药 ] 000597) 董事长 刘震 工作 调动 辞职 外 媒称 [ 阿里 ] 9'
         ,' 重组 [ 中金 ] 在线 成 泡影 [ 三五互联 ] 300051) 股东 提前 套现']
print(texts)
txt = pd.DataFrame(texts)
print(txt[0])

# seg = pkuseg.pkuseg()
# arr = []
# for i in txt[0]:
#     t = seg.cut(i)
#     print(i)
#     print(' |-: ', t)
#     l1 = []
#     for j in t:
#         l1.append(j)
#     sss = ' '.join(l1)
#     arr.append(sss)
#     print(' |-: ', arr)

# newtxt = pd.DataFrame(arr)
# print(newtxt)

# 创建词袋数据结构
# cv = CountVectorizer()
# cv_fit=cv.fit_transform(texts)
stp = ['你','我','他']
cvtxt = txt[0]
vec = CountVectorizer(stop_words=stp)
vec_fit = vec.fit_transform(cvtxt)
fitlist = vec_fit.toarray()

['股价 连续 涨停 股东 拟 减持 双 科技 涉嫌 提前 泄露 未 公开 信息 炒作 股价', '搜索引擎 输入 [ 尚赫 ] 发现 篇 [ 尚赫 ] 涉嫌 传销 虚假 宣传 跨 区 经营', '综艺股份 大兴 服装 拟 减持 公司 超 2%股份 [ 科新机电 ] 300092) 上市', '[ 四川双马 ] 000935)待注 资产 缩水 盈利 预测 下滑 [ 广电运通 ] 002', '    [ 宝象金融 ] 涉嫌 自融 项目 造假 请 停止 犯罪 信达 金控 字 介绍 又是 套路', '[ 铁岭新城 ] 000809) 股东 减持 2805万股 占 5. 1% [ 恒邦股份 ]', '三大 原因 [ 惠而浦 ] 会计 差错 前两年 净利 更正 减少 1. 89亿 [ 远程电缆', '[ 佛山照明 ] 000541) 董事长 辞职 [ 创兴资源 ] 600193) 虚假 陈述', '文章 深圳 检方 通报 翁涛 [ 深圳光彩投资控股集团有限公司 ] 社会 发行 虚拟 货币', '武生物( 300357) 股东 东方 富海 减持 公司 1. 2%股份 [ 同洲电子 ] 0', ' 华尔街 依然 喜欢 [ 通用 ] 电气 位 分析师 建议 卖出 [ 紫光古汉 ] 00059', ' [ 东北制药 ] 000597) 董事长 刘震 工作 调动 辞职 外 媒称 [ 阿里 ] 9', ' 重组 [ 中金 ] 在线 成 泡影 [ 三五互联 ] 300051) 股东 提前 套现']
0          股价 连续 涨停 股东 拟 减持 双 科技 涉嫌 提前 泄露 未 公开 信息 炒作 股价
1         搜索引擎 输入 [ 尚赫 ] 发现 篇 [ 尚赫 ] 涉嫌 传销 虚假 宣传 跨 区 经营
2         综艺股份 大兴 服装 拟 减持 公司 超 2%股份 [ 科新机电 ] 300092) 上市
3        [ 四川双马 ] 000935)待注 资产 缩水 盈利 预测 下滑 [ 广电运通 ] 002
4         [ 宝象金融 ] 涉嫌 自融 项目 造假 请 停止 犯罪 信达 金控 字 介绍 又是 套路
5        [ 铁岭新城 ] 000809) 股东 减持 2805万股 占 5. 1% [ 恒邦股份 ]
6        三大 原因 

In [19]:
fitlist

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
for l in fitlist:
    print(l)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0
 1 0 0 0 0 1 0 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 1 

In [15]:
str(vec.vocabulary_)[:100]

"{'股价': 13, '连续': 14, '涨停': 8, '股东': 12, '减持': 3, '科技': 11, '涉嫌': 7, '提前': 5, '泄露': 6, '公开': 2, '信息':"